#import.sql file
INSERT INTO `canvas8challenge`.`ROLES`(`RLS_ID`,`RLS_DESCRPTION`,`RLS_ROLE`)VALUES(0,"Admin ROLE","ROLE_ADMIN");
INSERT INTO `canvas8challenge`.`ROLES`(`RLS_ID`,`RLS_DESCRPTION`,`RLS_ROLE`)VALUES(1,"ORDINARY ROLE","ROLE_USER"); 